services:
  sun-panel:
    image: hslr/sun-panel:latest
    container_name: sun-panel
    restart: unless-stopped
    labels:
      com.centurylinklabs.watchtower.enable: "false"
    user: root
    privileged: true
    environment:
      TZ: ${TZ:-Asia/Shanghai}
    volumes:
      - /data/docker/config/sun-panel:/app/conf
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "${SUN_PANEL_PORT:-3002}:3002"
    networks:
      - homelab

networks:
  homelab:
    external: true
