services:
  dockge:
    image: louislam/dockge:1
    container_name: dockge
    restart: unless-stopped
    ports:
      - "5001:5001"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /data/compose/stacks:/data/compose/stacks
      - /data/docker/config/dockge:/app/data
    environment:
      - DOCKGE_STACKS_DIR=/data/compose/stacks
      - TZ=Asia/Shanghai

networks:
  default:
    name: homelab
    external: true
